//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int DealerId { get; set; }
        public int CustomerId { get; set; }
        public int VehicleId { get; set; }
        public int MechanicId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime BookingDateTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customers { get; set; }
        public virtual Dealer Dealers { get; set; }
        public virtual Mechanic Mechanics { get; set; }
        public virtual Service Services { get; set; }
        public virtual Vehicle Vehicles { get; set; }
    }
}
