//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementDBA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
